# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd618af4481905fb1670f124e02b48e13ed3963b88aff8eafc8f85fc24fe2591482ad1c416da38c1513acf5b867138461ab610e2ab940e1d93ee7e67fc9e3535

test:
  secret_key_base: 50462e8af8ab9b9f98236d88cb372472ed4b251ccbd48d30febe10aab998d15df5cb9e443164ff7c9b54f991c541d2936b67ef18b253b0380171de85aa38628a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
